openapi: "3.0.0"
info:
  version: 1.0.0
  title: StroeerKata
servers:
  - url: http://localhost:8080
paths:
  /user:
    get:
      summary: Retrieves Information about a user
      operationId: getUserInformation
      tags:
        - User
      parameters:
        - name: id
          in: query
          description: Id of the user
          required: false
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        "200":
          description: Information about the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInformation"
components:
  schemas:
    UserInformation:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        address:
          $ref: '#/components/schemas/Address'
        phone:
          type: string
        website:
          type: string
        company:
          $ref: '#/components/schemas/Company'
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
      required:
        - id
        - name
        - username
        - email
        - address
        - phone
        - website
        - company
        - posts

    Address:
      type: object
      properties:
        street:
          type: string
        suite:
          type: string
        city:
          type: string
        zipcode:
          type: string
        geo:
          $ref: '#/components/schemas/Geo'
      required:
        - street
        - suite
        - city
        - zipcode
        - geo

    Geo:
      type: object
      properties:
        lat:
          type: string
        lng:
          type: string
      required:
        - lat
        - lng

    Company:
      type: object
      properties:
        name:
          type: string
        catchPhrase:
          type: string
        bs:
          type: string
      required:
        - name
        - catchPhrase
        - bs

    Post:
      type: object
      properties:
        userId:
          type: integer
          format: int32
        id:
          type: integer
          format: int32
        title:
          type: string
        body:
          type: string
      required:
        - userId
        - id
        - title
        - body
